### ISSUE TITLE
Some words in the Wiki were translated incorrectly.

### ISSUE THREAD

**Issue by SofiaXu** [ZexWoo/Guides#1]
e.g.

English:
`The audio formats MPEG layer I, layer II, and layer III (MP3) have no native way of saving information about the contents, except for some simple yes/no parameters like "private", "copyrighted", and "original home" (meaning this is the original file and not a copy).`

Chinese Translation in wiki:
`MP3 并无存储内容相关信息的本地方案，除了一些简单的是／否参数，有如「private」、「copyrighted」和「original home」（意味着这是原始文件而非副本）。`

Correct Chinese Translation:
`MP3 并无存储内容相关信息的原生方案，除了一些简单的是／否参数，有如「private」、「copyrighted」和「original home」（表示这是原始文件而非副本）。`

i.e.

English:
`Error handling means that a codec can detect a corruption (flipped bit) in a file and warn the user about it, but it will still decode the rest of the file.`

Chinese Translation in wiki:
`错误处理指的是编解码器能够检测文件中的错误（比特翻转）并警告用户，但它能继续解码文件的剩余部分。`

Correct Chinese Translation:
`错误处理指的是编解码器能够检测文件中的错误（位反转现象）并警告用户，但仍将解码文件的其余部分。`

There are more incorrect words in the Wiki.

**Comment by ZexWoo** [comment]
已修正，感谢指正。

**Comment by SofiaXu** [comment]
ありがとう!
